#ifndef MAIN_DEFINES_H
#define MAIN_DEFINES_H

#include <avr/io.h>

#define GPIO_PORTB_DDR &DDRB
#define GPIO_PORTB_PORT &PORTB
#define GPIO_PINB_PIN &PINB

#define GPIO_PORTD_DDR &DDRD
#define GPIO_PORTD_PORT &PORTD
#define GPIO_PIND_PIN &PIND

#define LED_CAR_RED_PIN PB2
#define LED_CAR_YELLOW_PIN PB1
#define LED_CAR_GREEN_PIN PB0

#define LED1_PED_RED PB3
#define LED2_PED_GREEN PB4

#define BUTTON_PIN PD2

#endif